

create sequence product_seq start with 1 increment by 50;

create table desktop (
    product_id bigint generated by default as identity,
    form_factor varchar(255),
    primary key (product_id)
);
create table hard_disk (
    capacity integer not null,
    product_id bigint not null,
    primary key (product_id)
);

create table laptop (
    screen_size integer not null,
    product_id bigint not null,
    primary key (product_id)
);

create table monitor (
    diagonal float(53) not null,
    product_id bigint not null,
    primary key (product_id)
);

create table product (
    price float(53) not null,
    quantity integer not null,
    product_id bigint not null,
    manufacturer varchar(255),
    serial_number varchar(255),
    primary key (product_id)
);

alter table if exists desktop add constraint desktop_product_id foreign key (product_id) references product;
alter table if exists hard_disk add constraint hard_disk_product_id foreign key (product_id) references product;
alter table if exists laptop add constraint laptop_product_id foreign key (product_id) references product;
alter table if exists monitor add constraint monitor_product_id foreign key (product_id) references product;